import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "./AuthProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // verification: {
  //   google: "di0NZJvRdifmFmTUM1wP19Ir12R8KrZ9RfYlMFOm1qs",
  // },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={`font-sans`}>{children}</body>
      </html>
    </AuthProvider>
  );
}
